name: Continous Integration

on:
    pull_request:
        branches:
            - 'main'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: []
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  cache: 'npm'
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

    format:
        name: Format
        runs-on: ubuntu-latest
        needs: []
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  cache: 'npm'
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Format
              run: npm run format:ci

    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs: []
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  cache: 'npm'
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint:ci

            - name: Lint commits
              uses: wagoid/commitlint-github-action@v5

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: []
        strategy:
            matrix:
                node: [14, 16, 18]
                parallel: [1, 2, 3]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Chrome
              uses: browser-actions/setup-chrome@latest

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  cache: 'npm'
                  node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm ci

            - name: Test
              run: npm run test:ci
              env:
                  CHROME_BIN: chromium
